name: Docker Image CI

on:
  pull_request:
    branches: ['main', 'development']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [services/printify-service]

    steps:
      - uses: actions/checkout@v4
      - name: Build ${{matrix.service}} Docker image
        run: docker build . --file ${{matrix.service}}/Dockerfile -t ${{matrix.service}}:latest
